"""Variant prioritisation: filter, pair, score, rank.

The stage that turns a flagged variant set into a ranked list of candidate
hypotheses, each carrying its component score vector, its evidence (supporting
*and* contradicting), and the experiments that would resolve it.

Composition happens in ``mva.pipeline``: this package imports no peer stage, and
takes the phenotype and mechanism scores as arguments (GP-03).
"""

from __future__ import annotations

from mva.prioritization.filters import (
    FLAG_BENIGN_CONSEQUENCE,
    FLAG_COMMON_VARIANT,
    FLAG_HOMOZYGOUS_CALL,
    FLAG_LOW_FREQUENCY_VARIANT,
    FLAG_LOW_QUALITY_CALL,
    FLAG_NO_FREQUENCY_DATA,
    FLAG_PLAUSIBLE_CANDIDATE,
    FLAG_POSSIBLE_MOSAIC,
    HARD_FILTER_REASONS,
    FilterResult,
    HardFilterStream,
    apply_hard_filters,
    apply_soft_flags,
    iter_hard_filtered,
    iter_soft_flagged,
    select_candidate_variants,
)
from mva.prioritization.pairing import (
    DEFAULT_MAX_PAIRING_VARIANTS,
    DEFAULT_MAX_PAIRS_PER_GENE,
    FLAG_CAP_TRUNCATED,
    FLAG_PHASE_CIS,
    FLAG_PHASE_TRANS,
    FLAG_PHASE_UNKNOWN,
    FLAG_SINGLE_VARIANT,
    GeneCapEvent,
    PairCandidate,
    PairingResult,
    generate_pair_candidates,
    generate_pairs,
    infer_phase,
)
from mva.prioritization.ranking import (
    assign_discriminating_experiments,
    rank_pairs,
)
from mva.prioritization.scoring import (
    NEUTRAL_MECHANISM_SCORE,
    NEUTRAL_PHENOTYPE_SCORE,
    Contradiction,
    ScoredPair,
    collect_contradictions,
    composite_score,
    contradiction_penalty,
    score_analytical_validity,
    score_consequence,
    score_evidence_quality,
    score_inheritance,
    score_pair,
    score_rarity,
)
from mva.prioritization.selection import (
    CODING_CONSEQUENCE_TERMS,
    DROP_REASONS,
    KEEP_REASONS,
    SELECTION_SUBJECT_ID,
    SPLICE_CONSEQUENCE_TERMS,
    SelectionDecision,
    SelectionReport,
    SelectionResult,
    SelectionStream,
    SelectionThresholds,
    iter_selected,
    select_variants,
)

__all__ = [
    "CODING_CONSEQUENCE_TERMS",
    "DEFAULT_MAX_PAIRING_VARIANTS",
    "DEFAULT_MAX_PAIRS_PER_GENE",
    "DROP_REASONS",
    "FLAG_BENIGN_CONSEQUENCE",
    "FLAG_CAP_TRUNCATED",
    "FLAG_COMMON_VARIANT",
    "FLAG_HOMOZYGOUS_CALL",
    "FLAG_LOW_FREQUENCY_VARIANT",
    "FLAG_LOW_QUALITY_CALL",
    "FLAG_NO_FREQUENCY_DATA",
    "FLAG_PHASE_CIS",
    "FLAG_PHASE_TRANS",
    "FLAG_PHASE_UNKNOWN",
    "FLAG_PLAUSIBLE_CANDIDATE",
    "FLAG_POSSIBLE_MOSAIC",
    "FLAG_SINGLE_VARIANT",
    "HARD_FILTER_REASONS",
    "KEEP_REASONS",
    "NEUTRAL_MECHANISM_SCORE",
    "NEUTRAL_PHENOTYPE_SCORE",
    "SELECTION_SUBJECT_ID",
    "SPLICE_CONSEQUENCE_TERMS",
    "Contradiction",
    "FilterResult",
    "GeneCapEvent",
    "HardFilterStream",
    "PairCandidate",
    "PairingResult",
    "ScoredPair",
    "SelectionDecision",
    "SelectionReport",
    "SelectionResult",
    "SelectionStream",
    "SelectionThresholds",
    "apply_hard_filters",
    "apply_soft_flags",
    "assign_discriminating_experiments",
    "collect_contradictions",
    "composite_score",
    "contradiction_penalty",
    "generate_pair_candidates",
    "generate_pairs",
    "infer_phase",
    "iter_hard_filtered",
    "iter_selected",
    "iter_soft_flagged",
    "rank_pairs",
    "score_analytical_validity",
    "score_consequence",
    "score_evidence_quality",
    "score_inheritance",
    "score_pair",
    "score_rarity",
    "select_candidate_variants",
    "select_variants",
]
